# Creates a self-signed certificate (10 years) for HTTPS and config\tls.yaml.
# Needs openssl (found automatically if Git for Windows is installed).
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$openssl = (Get-Command openssl -ErrorAction SilentlyContinue).Source
if (-not $openssl) {
    foreach ($p in "$env:ProgramFiles\Git\usr\bin\openssl.exe", "${env:ProgramFiles(x86)}\Git\usr\bin\openssl.exe") {
        if (Test-Path $p) { $openssl = $p; break }
    }
}
if (-not $openssl) {
    Write-Host "openssl not found - HTTPS stays disabled (HTTP still works)." -ForegroundColor Yellow
    exit 0
}

$san = @("DNS:localhost", "DNS:$env:COMPUTERNAME", "IP:127.0.0.1")
Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } |
    ForEach-Object { $san += "IP:$($_.IPAddress)" }

New-Item -ItemType Directory -Force certs | Out-Null
$env:MSYS_NO_PATHCONV = "1"
& $openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -keyout certs/key.pem -out certs/cert.pem `
    -subj "/CN=cam2wall" -addext "subjectAltName=$($san -join ',')" 2>$null

@"
# Generated by scripts/make-cert.* - enables HTTPS on port 1985 (self-signed).
api:
  tls_listen: ":1985"
  tls_cert: "certs/cert.pem"
  tls_key: "certs/key.pem"
"@ | Set-Content -Encoding ascii config/tls.yaml

Write-Host "Certificate created for: $($san -join ', ')" -ForegroundColor Green
