#!/bin/sh
# Creates a self-signed certificate (10 years) for HTTPS and config/tls.yaml.
# Browsers show a warning once - expected for a self-signed certificate on a LAN.
set -e
cd "$(dirname "$0")/.."
command -v openssl >/dev/null || { echo "openssl not found - HTTPS stays disabled (HTTP still works)."; exit 0; }

SAN="DNS:localhost,DNS:$(hostname),IP:127.0.0.1"
for ip in $(hostname -I 2>/dev/null); do SAN="$SAN,IP:$ip"; done

mkdir -p certs
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -keyout certs/key.pem -out certs/cert.pem \
    -subj "/CN=cam2wall" -addext "subjectAltName=$SAN" 2>/dev/null
chmod 600 certs/key.pem

cat > config/tls.yaml <<YAML
# Generated by scripts/make-cert.* - enables HTTPS on port 1985 (self-signed).
api:
  tls_listen: ":1985"
  tls_cert: "certs/cert.pem"
  tls_key: "certs/key.pem"
YAML
echo "Certificate created for: $SAN"
